In [65]:
import pandas as pd

df = pd.read_csv(
    "../../datasets/EVProject_dataset.csv"
)

In [66]:
df.head()

,Timestamp,SoC,SoH,Battery_Voltage,Battery_Current,Battery_Temperature,Charge_Cycles,Motor_Temperature,Motor_Vibration,Motor_Torque,...,Load_Weight,Driving_Speed,Distance_Traveled,Idle_Time,Route_Roughness,RUL,Failure_Probability,Maintenance_Type,TTF,Component_Health_Score
0,2020-01-01 00:00:00,0.826099,0.941338,210.163881,-22.753095,27.149201,149.190930,48.496049,0.369095,113.435589,...,741.754518,103.421162,66.232383,0.520922,0.225970,260.503381,0,1,111.116697,0.852745
1,2020-01-01 00:15:00,0.064728,0.916059,364.000102,-27.701120,53.655101,171.702388,57.829492,1.449195,105.587160,...,769.134035,46.041935,3.146238,0.844005,0.204350,212.813954,0,2,179.229425,0.827616
2,2020-01-01 00:30:00,0.873643,0.908020,388.855089,-36.646406,29.559090,191.617645,46.518363,1.859045,119.610302,...,917.262931,59.588422,79.909148,0.992405,0.175125,273.394511,0,1,171.852663,0.876887
3,2020-01-01 00:45:00,0.853009,0.916476,370.570602,-37.609429,29.690283,111.881817,54.163681,0.381500,182.535625,...,600.598736,44.222285,0.774000,0.007615,0.213264,229.508442,0,0,165.221328,0.816290
4,2020-01-01 01:00:00,0.947540,0.913206,390.011904,-14.275808,28.864338,163.774377,42.075978,0.433927,173.298044,...,613.153029,41.374684,2.872124,0.771938,0.770257,257.302631,1,0,176.890659,0.744260

In [67]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"])
df = df.sort_values(by="Timestamp").reset_index(drop=True)

In [68]:
df["soc_1h"] = df["SoC"].shift(-4)

df["soc_6h"] = df["SoC"].shift(-24)

df["soc_24h"] = df["SoC"].shift(-96)

In [69]:
df["voltage_1h"] = df["Battery_Voltage"].shift(-4)

df["voltage_6h"] = df["Battery_Voltage"].shift(-24)

df["voltage_24h"] = df["Battery_Voltage"].shift(-96)

In [70]:
ROWS_PER_DAY = 96

df["soh_30d"] = (
    df["SoH"].shift(
        -(30 * ROWS_PER_DAY)
    )
)

df["soh_90d"] = (
    df["SoH"].shift(
        -(90 * ROWS_PER_DAY)
    )
)

df["soh_180d"] = (
    df["SoH"].shift(
        -(180 * ROWS_PER_DAY)
    )
)

In [71]:
df.tail()

,Timestamp,SoC,SoH,Battery_Voltage,Battery_Current,Battery_Temperature,Charge_Cycles,Motor_Temperature,Motor_Vibration,Motor_Torque,...,Component_Health_Score,soc_1h,soc_6h,soc_24h,voltage_1h,voltage_6h,voltage_24h,soh_30d,soh_90d,soh_180d
149079,2024-04-01 21:45:00,0.922618,0.922094,372.159103,-36.973790,34.326226,177.291880,46.395719,0.254364,179.298303,...,0.764277,0.81547,NaN,NaN,392.793709,NaN,NaN,NaN,NaN,NaN
149080,2024-04-01 22:00:00,0.975329,0.465340,393.324451,-194.459397,32.743188,199.079514,98.571606,1.996784,173.883422,...,0.729023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149081,2024-04-01 22:15:00,0.994075,0.447153,383.891555,-27.337149,56.224487,105.467625,54.498377,0.316342,126.157094,...,0.749751,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149082,2024-04-01 22:30:00,0.970045,0.925839,225.000063,-25.482119,30.423379,159.188604,56.634518,0.311548,121.171195,...,0.903158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149083,2024-04-01 22:45:00,0.815470,0.984781,392.793709,-23.348323,29.860318,199.654141,43.353572,0.421346,106.586042,...,0.745005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
df.isnull().sum()

Timestamp                     0
SoC                           0
SoH                           0
Battery_Voltage               0
Battery_Current               0
Battery_Temperature           0
Charge_Cycles                 0
Motor_Temperature             0
Motor_Vibration               0
Motor_Torque                  0
Motor_RPM                     0
Power_Consumption             0
Brake_Pad_Wear                0
Brake_Pressure                0
Reg_Brake_Efficiency          0
Tire_Pressure                 0
Tire_Temperature              0
Suspension_Load               0
Ambient_Temperature           0
Ambient_Humidity              0
Load_Weight                   0
Driving_Speed                 0
Distance_Traveled             0
Idle_Time                     0
Route_Roughness               0
RUL                           0
Failure_Probability           0
Maintenance_Type              0
TTF                           0
Component_Health_Score        0
soc_1h                        4
soc_6h                       24
soc_24h                      96
voltage_1h                    4
voltage_6h                   24
voltage_24h                  96
soh_30d                    2880
soh_90d                    8640
soh_180d                  17280
dtype: int64

In [73]:
print(df.shape)

(149084, 39)

In [74]:
df["Timestamp"].min()

Timestamp('2020-01-01 00:00:00')

In [75]:
df["Timestamp"].max()

Timestamp('2024-04-01 22:45:00')

In [76]:
df.isnull().sum().sort_values(ascending=False).head(20)

soh_180d               17280
soh_90d                 8640
soh_30d                 2880
soc_24h                   96
voltage_24h               96
soc_6h                    24
voltage_6h                24
voltage_1h                 4
soc_1h                     4
Battery_Current            0
Battery_Temperature        0
SoH                        0
SoC                        0
Timestamp                  0
Battery_Voltage            0
Charge_Cycles              0
Motor_Temperature          0
Motor_Torque               0
Motor_Vibration            0
Power_Consumption          0
dtype: int64

In [77]:
FEATURE_COLUMNS = [
    "SoC",
    "SoH",
    "Battery_Voltage",
    "Battery_Current",
    "Power_Consumption",
    "Driving_Speed"
]

### Building model for SoC

In [78]:
SOC_TARGETS = [
    "soc_1h",
    "soc_6h",
    "soc_24h"
]

In [79]:
soc_df = df.dropna(subset=SOC_TARGETS).copy()

In [80]:
print(soc_df.shape)

(148988, 39)

In [81]:
split_idx = int(
    len(soc_df) * 0.8
)

train_df = soc_df.iloc[:split_idx]

test_df = soc_df.iloc[split_idx:]

In [82]:
print(train_df.shape)

print(test_df.shape)

(119190, 39)
(29798, 39)

In [83]:
from sklearn.preprocessing import MinMaxScaler
import joblib

feature_scaler = MinMaxScaler()

train_df[FEATURE_COLUMNS] = (
    feature_scaler.fit_transform(
        train_df[FEATURE_COLUMNS]
    )
)

test_df[FEATURE_COLUMNS] = (
    feature_scaler.transform(
        test_df[FEATURE_COLUMNS]
    )
)

joblib.dump(
    feature_scaler,
    "soc_feature_scaler.pkl"
)

['soc_feature_scaler.pkl']

In [84]:
target_scaler = MinMaxScaler()

train_df[SOC_TARGETS] = (
    target_scaler.fit_transform(
        train_df[SOC_TARGETS]
    )
)

test_df[SOC_TARGETS] = (
    target_scaler.transform(
        test_df[SOC_TARGETS]
    )
)

joblib.dump(
    target_scaler,
    "soc_target_scaler.pkl"
)

['soc_target_scaler.pkl']

In [85]:
X_train = train_df[
    FEATURE_COLUMNS
].values.astype("float32")

y_train = train_df[
    SOC_TARGETS
].values.astype("float32")

X_test = test_df[
    FEATURE_COLUMNS
].values.astype("float32")

y_test = test_df[
    SOC_TARGETS
].values.astype("float32")

In [86]:
import numpy as np

WINDOW_SIZE = 24

def create_sequences(
    X,
    y,
    window_size
):

    X_seq = []
    y_seq = []

    for i in range(
        window_size,
        len(X)
    ):

        X_seq.append(
            X[
                i-window_size:i
            ]
        )

        y_seq.append(
            y[i]
        )

    return (
        np.array(X_seq),
        np.array(y_seq)
    )

In [87]:
X_train_seq, y_train_seq = (
    create_sequences(
        X_train,
        y_train,
        WINDOW_SIZE
    )
)

X_test_seq, y_test_seq = (
    create_sequences(
        X_test,
        y_test,
        WINDOW_SIZE
    )
)

In [88]:
X_train_seq.shape, y_train_seq.shape, X_test_seq.shape, y_test_seq.shape

((119166, 24, 6), (119166, 3), (29774, 24, 6), (29774, 3))

In [89]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    LSTM,
    Dense
)

model = Sequential([
    LSTM(
        32,
        input_shape=(
            X_train_seq.shape[1],
            X_train_seq.shape[2]
        )
    ),

    Dense(
        16,
        activation="relu"
    ),

    Dense(3)
])

c:\Users\shrey\OneDrive\Desktop\MY_Project\EV_Intelligence_System\Backend\venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [90]:
model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

In [91]:
history = model.fit(
    X_train_seq,
    y_train_seq,
    epochs=5,
    batch_size=32,
    validation_data=(
        X_test_seq,
        y_test_seq
    )
)

Epoch 1/5
3724/3724 ━━━━━━━━━━━━━━━━━━━━ 24s 6ms/step - loss: 0.0869 - mae: 0.2060 - val_loss: 0.0857 - val_mae: 0.2071
Epoch 2/5
3724/3724 ━━━━━━━━━━━━━━━━━━━━ 17s 5ms/step - loss: 0.0853 - mae: 0.2039 - val_loss: 0.0859 - val_mae: 0.2041
Epoch 3/5
3724/3724 ━━━━━━━━━━━━━━━━━━━━ 19s 5ms/step - loss: 0.0852 - mae: 0.2038 - val_loss: 0.0860 - val_mae: 0.2036
Epoch 4/5
3724/3724 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 0.0852 - mae: 0.2038 - val_loss: 0.0861 - val_mae: 0.1964
Epoch 5/5
3724/3724 ━━━━━━━━━━━━━━━━━━━━ 18s 5ms/step - loss: 0.0852 - mae: 0.2038 - val_loss: 0.0858 - val_mae: 0.2116

In [92]:
predictions = model.predict(
    X_test_seq[:10]
)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step

In [93]:
actual_predictions = (
    target_scaler.inverse_transform(
        predictions
    )
)

actual_targets = (
    target_scaler.inverse_transform(
        y_test_seq[:10]
    )
)

In [94]:
import pandas as pd

comparison_df = pd.DataFrame({
    "Actual_1H": actual_targets[:, 0],
    "Predicted_1H": actual_predictions[:, 0],

    "Actual_6H": actual_targets[:, 1],
    "Predicted_6H": actual_predictions[:, 1],

    "Actual_24H": actual_targets[:, 2],
    "Predicted_24H": actual_predictions[:, 2],
})

comparison_df

   Actual_1H  Predicted_1H  Actual_6H  Predicted_6H  Actual_24H  Predicted_24H
0   0.840663      0.785596   0.142604      0.776960    0.871138       0.763339
1   0.839103      0.778879   0.072805      0.772559    0.956154       0.759469
2   0.003300      0.776871   0.986276      0.768598    0.103881       0.762579
3   0.917454      0.776496   0.803443      0.767491    0.094673       0.761720
4   0.946288      0.777405   0.811579      0.768679    0.903558       0.761208
5   0.897908      0.785160   0.885778      0.774600    0.825820       0.764940
6   0.083128      0.777467   0.845948      0.769990    0.905496       0.759923
7   0.840239      0.776566   0.191492      0.774137    0.969182       0.758322
8   0.807396      0.776372   0.834826      0.770994    0.968672       0.764563
9   0.893390      0.774639   0.028017      0.765485    0.109861       0.762892

In [96]:
print(actual_predictions[:5])

print(actual_targets[:5])

[[0.78559583 0.77695966 0.7633388 ]
 [0.7788785  0.7725589  0.75946945]
 [0.7768713  0.76859814 0.7625792 ]
 [0.77649635 0.76749086 0.7617195 ]
 [0.7774053  0.7686789  0.7612081 ]]
[[0.8406635  0.14260355 0.87113816]
 [0.83910346 0.07280508 0.95615447]
 [0.00330009 0.9862758  0.10388073]
 [0.9174542  0.80344313 0.09467348]
 [0.9462881  0.81157875 0.90355784]]

In [97]:
from sklearn.metrics import mean_absolute_error

mae_1h = mean_absolute_error(
    actual_targets[:, 0],
    actual_predictions[:, 0]
)

mae_6h = mean_absolute_error(
    actual_targets[:, 1],
    actual_predictions[:, 1]
)

mae_24h = mean_absolute_error(
    actual_targets[:, 2],
    actual_predictions[:, 2]
)

print("MAE 1H :", mae_1h)
print("MAE 6H :", mae_6h)
print("MAE 24H:", mae_24h)

MAE 1H : 0.22192391753196716
MAE 6H : 0.32017219066619873
MAE 24H: 0.3047029376029968

In [98]:
preds = model.predict(
    X_test_seq[:1000]
)

preds = target_scaler.inverse_transform(preds)

actual = target_scaler.inverse_transform(
    y_test_seq[:1000]
)

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [99]:
from sklearn.metrics import mean_squared_error
import numpy as np

for i, horizon in enumerate(
    ["1H", "6H", "24H"]
):

    rmse = np.sqrt(
        mean_squared_error(
            actual[:, i],
            preds[:, i]
        )
    )

    print(
        horizon,
        "RMSE =",
        rmse
    )

1H RMSE = 0.2860778391240397
6H RMSE = 0.2869285870661131
24H RMSE = 0.2815963281723633

In [100]:
print(preds[:,0].min())
print(preds[:,0].max())
print(preds[:,0].mean())

0.77171457
0.7888079
0.77799964

In [101]:
print(actual[:,0].min())
print(actual[:,0].max())
print(actual[:,0].mean())

0.0005210445
0.9993583
0.7844475